### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by 7elix** [NamelessCoder/TYPO3.Fluid.Lint#4]
https://packagist.org/packages/namelesscoder/fluid-lint -> typo3.cms.

Thanks

**Comment by DanielRuf** [comment]
according to the docs it should be `typo3fluid/fluid-lint` but this does not exist.

**Comment by nitsan-technologies** [comment]
Hey!

I've also tried the following but does not work. Is there any update?

`composer require typo3fluid/fluid-lint`
Error: Could not find a matching version of package typo3fluid/fluid-lint.

`composer require namelesscoder/fluid-lint`
Error: Failed to clone https://github.com/NamelessCoder/TYPO3.Fluid.git via https, ssh protocols, aborting.

Cheers!

**Comment by bmack** [comment]
Sorry all for the long delay, here we go

https://packagist.org/packages/typo3fluid/fluid-lint

**Comment by NamelessCoder** [comment]
The package will need a new release as the dependencies are currently set to `namelesscoder/fluid` which is where Fluid Standalone existed before it was added to the official organisation. It is unlikely to work even if aliasing `typo3fluid/fluid as namelesscoder/fluid`.

**Comment by DanielRuf** [comment]
> The package will need a new release as the dependencies are currently set to `namelesscoder/fluid` which is where Fluid Standalone existed before it was added to the official organisation. It is unlikely to work even if aliasing `typo3fluid/fluid as namelesscoder/fluid`.

Let's see how a current build looks like: https://github.com/TYPO3/Fluid.Lint/pull/6

**Comment by NamelessCoder** [comment]
`dev-master` should work, `1.0.0` will not - I expect we need 2.0.0 with the new deps.

**Comment by nitsan-technologies** [comment]
Hey @bmack 
Thanks for your quick support.

Hey @NamelessCoder 
Thanks for your great work and excited for next version. Yeah, It works with dev-master. Can you please help me with the following stuff?

I'm trying the package at https://gitlab.com/sanjay_nitsan/site_default/-/jobs/228752312

- Getting an error "Warning: file_get_contents(/Resources/Private/Templates/Default.html): failed to open stream: No such file or directory"
- Is it feasible to define whole Fluid folder eg., /Resources/Private/Templates/ instead of mentioning each file?

Cheers!

**Comment by DanielRuf** [comment]
> Getting an error "Warning: file_get_contents(/Resources/Private/Templates/Default.html): failed to open stream: No such file or directory"

Does that path exist? Looks like an absolute path.

**Comment by nitsan-technologies** [comment]
Hey @DanielRuf 

Thanks for your quick response. Yes, I'm trying to setup Gitlab-CI, And path is exist, you may check this open repo https://gitlab.com/sanjay_nitsan/site_default/tree/master ;) Do you have any idea to lint whole folder?

Cheers!

**Comment by DanielRuf** [comment]
> /Resources/Private/Templates/Default.html

This is an absolute path, not a relative one.

**Comment by nitsan-technologies** [comment]
Hey @DanielRuf 

Thanks! Yep, just corrected and works well now. Just question, Is it feasible to Lint whole folder?

Cheers!

**Comment by DanielRuf** [comment]
> Is it feasible to Lint whole folder?

Makes sense as this will scan / lint all file for issues (which is normally done with phpcs and other tools too). A list of files to include for the linting task would be hard to maintain.
