### ISSUE TITLE
Scan/Lint Whole Folder

### ISSUE THREAD

**Issue by nitsan-technologies** [NamelessCoder/TYPO3.Fluid.Lint#7]
Hey!

**What's current issue**
According to last discussion at https://github.com/TYPO3/Fluid.Lint/issues/4#issuecomment-500817153 It would be nice to have features to scan/lint whole folder.

**What expects?**
The developer can just define folder, and it will automatically find all the Fluid files to scan/lint.

**Example**
`- .Build/bin/fluid-lint Resources/Private/`

Cheers!

**Comment by lolli42** [comment]
This project is being archived: It is unmaintained since seven years and nobody seems to step in.
In case we want to implement a general linter to Fluid, it should be added to Fluid directly.
